analogdevicesinc/libsmu

cli.cpp
libsmu.hpp
session.cpp

I was messing around and noticed it segfaulted when I didn't have the proper USB permissions. With these fixes it should at least provide users more notice of what they're doing wrong instead of segfaulting.
I should also note I was able to segfault pixelpulse2 somewhat consistently by shorting the 5V pin, but haven't tracked down a fix for that yet. Probably something similar though with usb device handling on corner error conditions.

Extend error handling when we can't properly initialize a device

---

session.cpp

This avoids a segfault in pixelpulse2 when first starting the app and
then plugging in a device without full access permissions to it.

don't try to access device when probing failed

---

pysmu.cpp

When appending to lists, the refcount of an object gets incremented so
we need to decrement it in order for the object to be removed when the
list gets removed.

pysmu: drop the ref count for individual samples, otherwise they leak

---

pysmu-proto.py
pysmu.cpp

Also fixes the ordering of the output wave enum usage to match what's
currently defined for the backend.

pysmu: add support for the stairstep output waveform

---

pysmu.cpp

This should fix all the memory leaks that occur when running get_dev_info().
It's trivial to see the leaks if you run something like the following (not that you'd do something like that in real code):
```
import pysmu                                                                                                                                                                                                        
pysmu.setup()                                                                                                                                                                                                       
for i in xrange(10000000000000): …
```

pysmu: fix memory leaks when querying the device info

---

libsmu.hpp
session.cpp

Methods that touch the m_available_devices should not be able to do so simultaneously from different threads.

adds mutex around m_available_devices

---

src/libsmu.hpp

This fix makes sure that the last step of a stairstep signal is generated.
When norm_phase goes from [0.0, to 0.99..] floorf(norm_phase*10)/10
will go from [0.0 to 0.9]. This leads to the last stairstep never
being generated because of the missing 1.0 value.
Signed-off-by: Dan <Dan.Nechita@analog.com>

src/libsmu.hpp: Add missing step when generating staristep signal

---

CMakeLists.txt
src/libsmu.hpp

It seems that `functional` header must be included to properly compile under Arch Linux.

Fixed compiling issue related to C+11 on ArchLinux

---

appveyor.yml

Provide ZIP artifacts compiled with MinGW that can be linked
to any application. Do not provide an installer for these
builds.
Signed-off-by: Alexandra Trifan <Alexandra.Trifan@analog.com>

appveyor.yml: Create MinGW builds for Windows 32 bit and 64 bit.

---

bindings/python/pysmu/cpp_libsmu.pxd
bindings/python/pysmu/libsmu.pyx
include/libsmu/libsmu.hpp
src/device_m1000.cpp
src/device_m1000.hpp

Hi:
These changes, along with new features in m1k-fw, allow access to the ADC and DAC configuration registers to provide 200KSPS operation modes. I've tested these changes using Mingw32 compiler on Windows and they should not interfere with any existing software. I've made the changes with a minimalistic style sufficient to access the new features provided by my changes to m1k-fw. I think these are the only changes I ended up making. In the process of finding my way around and figuring out how to make the software tools work I may have touched other files and not remembered.
Setting up and using these 200KSPS configurations is more advanced than the typical user would be doing. I've added settings for 4 of the 6 possible combinations and another that just passes raw, unscaled and …

Libsmu changes to access ADC and DAC config registers

---

src/device_m1000.cpp

This was previously fixed with commit 41e2924b933b00e7732c18825d0ea98ec82cf04e
however the change was lost after merge commit 6e5d7af7786f8a8b6b0390a1ea382ae10b52a17d

device_m1000.cpp: fix variable delay in multidevice configuration

---

.travis.yml
bindings/python/pysmu/cpp_libsmu.pxd
bindings/python/pysmu/libsmu.pyx
examples/hotplug.cpp
include/libsmu/libsmu.hpp
src/cli/smu.cpp
src/session.cpp

In this version, we have changed the hotplug mechanism from libsmu. This is because in the last versions of libusb, they have changed the way it works. On the latest versions, when a hotplug signal is emitted (and the callback is started), the device becomes busy, until the callback ends. This thing makes the hotplug mechanism from libsmu inoperative, because it is (almost) impossible to synchronize the callback end time and libsmu calls on the device. When this branch will be merged into master, we will not use the old version of libusb anymore and will use the latest available libusb version (link to the libusb github repository: https://github.com/libusb/libusb).
Therefore we have removed  the hotplug_attach and hotplug_detach methods from libsmu and the "-p, --hotplug-devices" option …

Libusb hotplug removed and crash on close bug solved.

---

include/libsmu/libsmu.hpp
src/session.cpp

Implemented a workaround for the bug from libusb. On Windows, libusb was not anymore able to open e device's interface for the second time.
To solve this, we save the libusb handle received by the device on the first open and use it on further open tries.
Signed-off-by: Cristi Iacob <Cristian.Iacob@analog.com>

Libusb bug workaround.

---

bindings/python/pysmu/libsmu.pyx

Python3 doesn't support Exception.message() anymore. Changed this in order to work on both Python2 and Python3.

Solved some Python 2-3 compatibility problems.

---

bindings/python/setup.py

The cython file is generated in the first build. Any modification done in
the source files (libsmu.pyx for example) is not propagated to the
python bindings. In order to do so, the libsmu.cpp (generated) file
should be removed after every build.
To fix this, we configure setup.py to always regenerate the extension files.
Signed-off-by: Alexandra.Trifan <Alexandra.Trifan@analog.com>

bindings/python/setup.py: Always regenerate cython extensions.

---

bindings/python/pysmu/libsmu.pyx

The queue_size parameter wasn't initialized with the default value and this fact was producing sometimes runtime errors.
We have fixed this and initialize it with the default value from libsmu.

Pysmu session constructor fix.

---

include/libsmu/libsmu.hpp
src/device_m1000.cpp
src/device_m1000.hpp
src/session.cpp

1) Scanning while a device was already running distorted the signal (probably because of the control_transfer call - done in order to get the serial device). We modified the scanning to identify devices based on USB bus_id an USB address. 
2) Unplugging a device from a multi device session caused the application to block because of a mutex which was not properly unlocked.

Fix some session bugs

---

appveyor.yml

The appveyor build crashed on the Python2 build for dist files. This is most probably caused because Python2 is outdated. Although other libsmu Python2 builds are successful and provide the neccessary bindings for Python2.

appveyor: removed Python2 dist files.

---

src/session.cpp

When scanning for samba devices Pixelpulse freed the found device list making them unable to be flashed.

Firmware update bug fix.

---

CMakeLists.txt

Signed-off-by: Alexandra Trifan <Alexandra.Trifan@analog.com>

CMakeLists.txt: Use "/usr/local" as the default install path instead of "/usr".

---

src/session.cpp

The cancel() call is needed in order to cancel the current transfers from each connected device before turning them off, when running in a continuous fashion. This prevents libsmu from getting into a deadlock because of the m_state mutex locked in the run() method.
The m_cancellation flag must be removed from the if-statement because it is only set in the device->cancel() method, preventing the program from entering this if statement.
This bug was introduced in [0548b85](https://github.com/analogdevicesinc/libsmu/commit/b8e7e2e2f0e1a1940bcf1ca2d1bd555ccd1a6bc2). The introduced bug has hidden by Pixelpulse, which I have used to test that modification. In Pixelpulse, session->close() was called before session->end(), solving the above mentioned threading issue.
Signed-off-by: Cristi Iacob …

session.cpp: fixed cancellation bug.

---

README.md

The command in the documentation for installing the linux dependencies has a typo
Fixes #172

Fix typo in Linux dependencies

---

bindings/python/bin/pysmu

1/ Fix "ImportError: cannot import name 'urlretrieve'"
2/ Fix "ModuleNotFoundError: No module named 'urllib2'"
Fixes #174

bin/pysmu: Fix urllib imports for python2 and python3 compatibility

---

appveyor.yml
bindings/python/setup.py
dist/libsmu-x64.iss.cmakein
dist/libsmu-x86.iss.cmakein

The following changes were made:
- the Visual Studio 2015 image wasn't compatible with pacman anymore. Upgraded it to VS 2019 and its specific dependencies (boost 1.73 and the current VS redistributables);
- Updated supported Python versions: removed 3.6 and added 3.8;
- In Python 3.8 the .pyd/.dll file import mechanism was changed. Implemented the necessary modifications to support pysmu's importing for Python 3.8.
- updated libusb version to 1.0.23; v1.0.24 is not compatible with the Python bindings because it defines some symbols which conflicts with the Python libraries;
- dpinst.exe is not supported in the latest Windows 10 releases; changed it with pnputil.exe;
- iscc removed some language packages; I removed them from out installer as well;
- removed some redundant commands from …

Appveyor fixes

---

bindings/python/pysmu/utils.py

Python 3.10 changed the module of Iterable to have a different path. This fixes that issues and is backward compatible.
Signed-off-by: Travis F. Collins <travis.collins@analog.com>

Fix py3.10 issue
